### ISSUE TITLE
Test different input file format

### ISSUE THREAD

**Issue by dominikpeter** [bmsuisse/lakeapi#33]
We should also test for CSV, Excel, Json inputs. Otherwise, we should not claim to be able to load different file formats in the docs :-).

**Comment by aersam** [comment]
we have some in the tests.... 
To see what's not tested you can also run tests locally and get coverage report as nice html: ` poetry run pytest --cov=bmsdna tests --benchmark-skip --cov-report html`

Seems to be mostly the operators (I already added some config for it, tests pending)

**Comment by dominikpeter** [comment]
👍
