### ISSUE TITLE
Correctly implement arrow-stream

### ISSUE THREAD

**Issue by dominikpeter** [bmsuisse/lakeapi#41]
Get rid of arrow-stream as a response type.

**Comment by aersam** [comment]
why? :) I used that one for streamlit. is it the same as arrow? or does it not have any true benefits?

**Comment by dominikpeter** [comment]
We might have to check how ROAPI is doing it. The idea would be to stream the arrow batches.

**Comment by aersam** [comment]
Might be more of a decoding issue. To get a dataset you'd need to split the response to multiple files. I can try to do a sample

**Comment by dominikpeter** [comment]
There are two different Mime types

vnd.apache.arrow.stream
vpn.apache.arrow.file

https://arrow.apache.org/faq/

We recommend “.arrow” as the IPC file format file extension:

https://arrow.apache.org/docs/format/Columnar.html#ipc-file-format

and “.arrows” for the IPC streaming format file extension:

https://arrow.apache.org/docs/format/Columnar.html#ipc-streaming-format
