### ISSUE TITLE
Use of Azure Authentication

### ISSUE THREAD

**Issue by dominikpeter** [bmsuisse/lakeapi#48]
Do we need it to integrate the API with Streamlit or other Azure hosted Apps?

**Comment by aersam** [comment]
No, unless we want to authenticate to storage using user context

**Comment by dominikpeter** [comment]
Then we have to discuss how to do streamlit authentication :-)

**Comment by aersam** [comment]
I think we should drop authentication entirely and do it as a middleware - unless we want to have some RLS implemented in the lakeapi directly, but that would impose lot's of questions
