### ISSUE TITLE
Drop create delta table can result in internal error

### ISSUE THREAD

**Issue by dominikpeter** [bmsuisse/lakeapi#49]
DuckDB probably holds information in memory. Drop re-create a delta table can therefore cause an internal error (file not there anymore). In this case we should catch the error and do a manual refresh.

**Comment by aersam** [comment]
We should add a test fot this
Could also be that delta-rs caches

**Comment by dominikpeter** [comment]
or this:
https://github.com/bmsuisse/lakeapi/blob/98952655b3342bbc4961129d8f1b13f6f2edb37c/bmsdna/lakeapi/context/df_duckdb.py#L221
