### ISSUE TITLE
Considering in memory

### ISSUE THREAD

**Issue by dominikpeter** [bmsuisse/lakeapi#62]
For optimal performance, it would still sometimes make sense to keep small data in memory.

We can discuss that. If we implement it right, we should not have issues.

**Comment by aersam** [comment]
Maybe try using one global DBContext / DuckDB Connection and see if duckdb/polars do what we want

**Comment by dominikpeter** [comment]
I would suggest a global dict that holds the key (table name) and the pyarrow table in memory.
