### ISSUE TITLE
It can block

### ISSUE THREAD

**Issue by dominikpeter** [bmsuisse/lakeapi#75]
I was able to block the API. We might have to reverse and still not use copy into.

**Comment by aersam** [comment]
would be interesting if we can repo somehow. I have my test script under tests/duckdb_tests.py . With the view approach I was able to run the loop there 100 times without trouble. Without, it blocks randomly after at most 50 iterations

**Comment by dominikpeter** [comment]
Probably you re-created it with the open DuckDB issue.
