### ISSUE TITLE
Change versioning path

### ISSUE THREAD

**Issue by dominikpeter** [bmsuisse/lakeapi#78]
Per default, API Management wants to add the versioning at the end. Therefore, we should change the pattern 
from `api/v1` to `v1/api`.

But this would mean a breaking change, and we have to be careful and also change all clients relying on the existing endpoints.

**Comment by aersam** [comment]
really? Everything else uses api/v1, including Microsofts .Net ... we cannot adjust API Management? If we do it it gets complicated with the various internal clients we already have
