### ISSUE TITLE
Migrate away from pypika

### ISSUE THREAD

**Issue by aersam** [bmsuisse/lakeapi#99]
use either sqlglot or ibis

**Comment by dominikpeter** [comment]
To solve #98

**Comment by dominikpeter** [comment]
After some research I think we should go for Ibis.

**Comment by aersam** [comment]
seems to be quite involved... not sure ibis is a good fit anymore. issues so far:

- reading from existing select using subselect not supported
- custom functions either not documented or not possible at all. this is a requirement for duckdb's semantic search

**Comment by dominikpeter** [comment]
Ibis uses sqlglot in the backend too.
Let’s try this…

**Comment by dominikpeter** [comment]
Let's bring the sql query builder to Rust

https://crates.io/crates/sql_query_builder

**Comment by aersam** [comment]
Pypika is coming to live again, so migrating is no prio I guess: https://github.com/kayak/pypika/issues/737
